language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/search.js
- ./ci/build.js
- ./ci/travis/set_git_config.js
- git add .
- git commit -m "[ci skip]Update from Travis CI"
- git push origin HEAD:master
env:
  secure: "ICiM3AKYyWZo3FancMqPYSHfb2pCpy5WNV+qrqKCfjr0jbI1/oh1WnJXR0cK/IS+LD0YHw2dib0xzTBiG4j2BdqLhIQG7H/eBu/NyXc7lM5QuxQPfFrZsH3xcJkf2sI8WslW7sOLW/iT1iyNTzWWDOsBFiWtp7OExZhM9+Pu/RW0eUeZV3aZe1cusWewodHjobCQTIY/3X/nL8jQhTze2OUrqpnpJ3tzX9lm2jd44CkCcVDPOPLHXb8hSVTtRAIcHymhnu0hwDBDRAyiNbtCdeOPTw5Qf2d7CN7BWKXPtOIYXViQJfNcTjiwM7JpX/Nqwr5RqXCaRLsF9Ll6LEJn79lirDYTR4tcYro7Gerh1XKodywlI5TcGFrSyLtVHVju0rPV93GJ7yeHwgPO9w7VCu1Df5QgWg0fe30fO9ugSEQfzPXgMX1Orda+No68ehPJHNnuvumTrHtCbmruRd6MlBtxLPkGxFzu3EcHrx+tlNud+uubgqvfnaeAZ8yudAso1NMnEoNmeEgSRc01f2wJsXZfSz1Fi9d9EIQSJbkIvRJmx5zvyaPBmEOZo1jzt8QhSNwi0FrQ3pl6xqda8ZK9iuJqf3J6wSYIUxRIzq3l8d0dS9LRhVgO5GG63iTW84ZOYbDZJsAqHF5A6UWts9iYA7/eLAG3OblPvNcqEvM7PJ4="